name: CI

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-20.04
    env:
      MIX_ENV: test
    strategy:
      fail-fast: false
      matrix:
        include:
          - pair:
              elixir: '1.5.3'
              otp: '20.1.7.1'
          - pair:
              elixir: '1.6.6'
              otp: '20.3.8.26'
          - pair:
              elixir: '1.6.6'
              otp: '21.0.9'
          - pair:
              elixir: '1.8.2'
              otp: '21.3.8.21'
          - pair:
              elixir: '1.10.4'
              otp: '23.0.4'
          - pair:
              elixir: '1.11.3'
              otp: '23.2.7'
          - pair:
              elixir: '1.12.3'
              otp: '24.3.4'
          - pair:
              elixir: '1.13.4'
              otp: '25.0'
          - pair:
              elixir: '1.14.3'
              otp: '25.3'
          - pair:
              elixir: '1.15.1'
              otp: '26.0.2'
          - pair:
              elixir: '1.17.1'
              otp: '27.0'
            lint: lint
    steps:
      - uses: actions/checkout@v2

      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.pair.otp}}
          elixir-version: ${{matrix.pair.elixir}}

      - name: Install Dependencies
        run: mix deps.get --only test

      - run: mix format --check-formatted
        if: ${{ matrix.lint }}

      - run: mix deps.get && mix deps.unlock --check-unused
        if: ${{ matrix.lint }}

      - run: mix deps.compile

      - run: mix compile --warnings-as-errors
        if: ${{ matrix.lint }}

      - run: mix test --include openssl
